<?php
/*   Copyright (C) Tomasz J. Kotarba, 2004
 *
 *   Do you want to contact me? I live in Cracow/Poland/EU so unless
 *   you live in this lovely and ancient city, you will most likely want to
 *   send me an e-mail... here is the address:
 *
 *   Tomasz J. Kotarba <tomasz@kotarba.net>
 *
 *
 *   This file is part of CACANMS.
 *   
 *   CACANMS is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *   
 *   CACANMS is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *   
 *   You should have received a copy of the GNU General Public License
 *   along with CACANMS; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/

require_once $common_components.'/network_loader.php';

require_once $classes."/networking/dhcp/configuration_file.inc.php";
require_once $classes."/networking/dhcp/string_option.inc.php";
require_once $classes."/networking/dhcp/routers_option.inc.php";
require_once $classes."/networking/netmask.inc.php";

$domain_name_option=new String_Option('domain-name',$domain_name);

foreach($domain_name_servers as $server)
 $DNSs[]=new IP($server);
$domain_name_servers_option=new Option('domain-name-servers',$DNSs);
unset($DNSs,$server);

$broadcast_address_option=new Option('broadcast-address',$local_network->address->Broadcast_Address());

foreach($netbios_name_servers as $server)
 $NBNSs[]=new IP($server);
$netbios_name_servers_option=new Option('netbios-name-servers',$NBNSs);
unset($NBNSs,$server);

$subnet_mask=$local_network->address->IP_prefix->to_Netmask();
$subnet_mask=$subnet_mask->to_String();

$dhcp_header="
# dhcpd.conf
#
# configuration file for ISC dhcpd
#
# GENERATED by CACANMS
#
  
  
shared-network MYNETWORK
{
 subnet ".$local_network->address->IP_to_String()." netmask ${subnet_mask}
 {
  ".$domain_name_option->to_String()."
  ".$domain_name_servers_option->to_String()."
  ".$broadcast_address_option->to_String()."
  ".$netbios_name_servers_option->to_String()."
  option netbios-node-type 2;
  option netbios-scope \"\";
  deny unknown-clients;
 }
}

group
{
use-host-decl-names on;

";

$dhcp_footer="\n}\n";

$dhcp_configuration_file=new Configuration_File($output_files['dhcpd file'],$dhcp_header,$dhcp_footer);

$hosts=$local_network->Find_Hosts('^[^H]+$','flags');

foreach($hosts as $host)
{
 if($host->flags->no_dhcp)
  continue;
 $router='r'.$host->router;
 if(array_key_exists($router,$routers))
  $router=new Routers_Option(new IP($routers[$router]));
 else
  $router=null;

 foreach($host->MAC as $hwaddr)
   $dhcp_configuration_file->Add_Host_Declaration(new Host_Declaration($host->hostname,$hwaddr,$host->IP,$router));
}
unset($subnet_mask,$domain_name_option,$domain_name_servers_option
      ,$broadcast_address_option,$netbios_name_servers_option,$router,$hwaddr);
?>
